=== coupelon/tdrop/tdengines/teardrop_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<xs:schema id="Teardrop"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   version="1.0"
	   xml:lang="EN">
  <xs:element name="regexp" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        The regexp element is a string containing a regular expression
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  
  <xs:element name="url" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        This can be an url, of a part of it
      </xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="inputfield">
    <xs:annotation>
      <xs:documentation>
        This field represents the parameters of a query
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="name" type="xs:string"/>
          <xs:attribute name="value" type="xs:string"/>
          <xs:attribute name="num" type="xs:integer"/>
          <xs:attribute default="yes" name="escape" type="ynType"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="ynType">
    <xs:annotation>
      <xs:documentation>
        yes/no type
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="yes"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="methodType">
    <xs:annotation>
      <xs:documentation>
        GET/POST type
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="GET"/>
      <xs:enumeration value="POST"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="engine">
    <xs:annotation>
      <xs:documentation>
        This is the base of every engines. 
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="name" type="xs:string">
          <xs:annotation>
            <xs:documentation>
              The "name" element defines the human readable name of the engine
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        
        <xs:element name="separator">
          <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
          </xs:complexType>
        </xs:element>
        
        <xs:element minOccurs="0" name="revision" type="xs:integer">
          <xs:annotation>
            <xs:documentation>
              This optional element represents the version of the xml file
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        
        <xs:element minOccurs="0" name="charset" type="xs:string">
          <xs:annotation>
            <xs:documentation>
              The charset of the pages to parse. It is an optional yet important
              field as some search engines won't provide this information to the
              browser.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        
        <xs:element minOccurs="0" name="updatable" type="xs:string">
          <xs:annotation>
            <xs:documentation>
              This field, if set to yes, will prevent the engine to be automaticaly
              updated. This will ensure that the self modified engines (such as Google
              Api) dont get updated.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        
        <xs:element minOccurs="0" name="terms" type="xs:anyURI">
          <xs:annotation>
            <xs:documentation>
              If present, this field indicates the url to be followed in order to
              get the search engine's terms of use (which might contain information
              concerning the right to meta-search this engine).
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        
        <xs:element minOccurs="0" maxOccurs="unbounded" name="header" type="xs:string">
          <xs:annotation>
            <xs:documentation>
              With this, one could add several header which are required by the engine,
              such as UserAgents, ContentType...
            </xs:documentation>
          </xs:annotation>
        </xs:element>

        <xs:element maxOccurs="unbounded" minOccurs="0" name="init">
          <xs:annotation>
            <xs:documentation>
              With those fields, you can initialize a connection to a server. Some search
              engines requires the browser to follow some redirections and/or to submit some
              information before accepting queries.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" ref="regexp"/>
              <xs:element ref="url"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" ref="inputfield"/>
            </xs:sequence>
            <xs:attribute name="method" type="methodType"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="query">
          <xs:annotation>
            <xs:documentation>
              This unique field should be use to specify the query giving the search results.
              If any other operations is required before the query submission, please use "init"
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="url"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" ref="inputfield"/>
            </xs:sequence>
            <xs:attribute name="method" type="methodType"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="result">
          <xs:annotation>
            <xs:documentation>
              This is the model of the result page. With the regexp field, Teardrop
              knows how to parse the results from the page. The "field" field tells
              teardrop how to deal with each results found.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="regexp"/>
              <xs:element maxOccurs="unbounded" name="field">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="num" type="xs:integer"/>
                      <xs:attribute default="no" name="striphtml" type="ynType"/>
                      <xs:attribute default="yes" name="escape" type="ynType"/>
                      <xs:attribute name="name" type="xs:string"/>
                      <xs:attribute default="yes" name="comparable" type="ynType"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element minOccurs="0" name="nextinput">
          <xs:annotation>
            <xs:documentation>
              This part is required when there are more results to found in
              a following page (a next page). The regexp, the url and the inputfield
              are there to identify such pages, so that Teardrop can parse the newly
              found page for results, then again looking for the next page as long as
              there are some unvisited pages or enough results have been found.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" ref="regexp"/>
              <xs:element minOccurs="0" ref="url"/>
              <xs:element maxOccurs="unbounded" ref="inputfield"/>
            </xs:sequence>
            <xs:attribute name="method" type="methodType"/>
          </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== coupelon/tdrop/trunk/tdengines/xml/arxiv.xml
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>arXiv.org</name>
  <separator value=" " />
	<charset>UTF-8</charset>
  <header>User-Agent: Mozilla/5.0</header>
	<query method="POST">
    <url>http://arxiv.org/search</url>
    <inputfield name="query" value="%q" />
    <inputfield name="searchtype" value="all" />
  </query>
  <result>
    <regexp><![CDATA[\+1">.*?href="([^"]*)">abs.*?Title:\s*(.*?)<br\s*/>(.*?)&nbsp;<br\s*/>]]></regexp>
    <field num="1" comparable="yes" name="url">http://arxiv.org%s</field>
    <field num="2" striphtml="yes" name="title" />
    <field num="3" striphtml="yes" name="abstract" />
  </result>
	<nextinput method="GET">
		<regexp><![CDATA[<a\s+href="([^"]*)">Next 25 results</a>]]></regexp>
		<inputfield escape="no" num="1" name="" value="http://arxiv.org%s" />
	</nextinput>
</engine>

=== coupelon/tdrop/tdengines/xml/citebase.xml
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>Citebase</name>
  <separator value="+" />
	<charset>UTF-8</charset>
	<query method="GET">
		<url>http://www.citebase.org/search</url>
		<inputfield name="type" value="metadata" />
		<inputfield name="maxrows" value="10" />
		<inputfield name="title" value="%s" />
		<inputfield name="order" value="DESC" />
		<inputfield name="rank" value="paperimpact" />
	</query>
	<result>
		<regexp><![CDATA[<div><a\s+target="_top"\s+href="([^"]*)"\s+class="abs_title">(.*?)</a>.*?</div>(.*?)</div>.*?<div>\s*(.*?)</div>]]></regexp>
		<field num="1" comparable="yes" name="url">http://www.citebase.org%s</field>
		<field num="2" striphtml="yes" name="title" />
		<field num="4" striphtml="yes" name="abstract" />
		<field num="3" striphtml="yes" name="abstract">(%s)</field>
	</result>
	<nextinput method="GET">
		<regexp><![CDATA[<a\s+target="_top"\s+href="([^"]*)">Next]]></regexp>
		<inputfield escape="no" num="1" name="" value="%s" />
	</nextinput>
</engine>

=== coupelon/tdrop/trunk/tdengines/xml/easybourse-forums.xml
<!--
# Teardrop Engine File
-->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>EasyBourse Forums</name>
	<separator value=" " />
	<charset>ISO-8859-1</charset>
	<query method="POST">
		<url>http://www.easybourse.com/forum-bourse/recherche/?forum=</url>
		<inputfield name="MotsCles" value="%q" />
		<inputfield name="TypeRecherche" value="message" />
	</query>
	<result>
		<regexp><![CDATA[href="([^"]*)"\s+class="TexteForumViolet"\s+onmouseover="info_bulle\('','(.*?)','[^>]*><u>([^<]*)]]></regexp>
		<field num="1" comparable="yes" name="url">http://www.easybourse.com/%s</field>
		<field num="2" striphtml="yes" name="abstract" />
		<field num="3" striphtml="yes" name="title" />
	</result>
	<nextinput method="GET">
		<regexp><![CDATA[np=([0-9]+)\&PHPSESSID=([^"]*)"\s+class="TexteForumBlancPetitGras">page suivante</a>]]></regexp>
		<url>http://www.easybourse.com/forum-bourse/recherche/</url>
		<inputfield name="MotsCles" value="%q" />
		<inputfield name="TypeRecherche" value="message" />
		<inputfield num="1" name="np" value="%s" />
		<inputfield num="2" name="PHPSESSID" value="%s" />
	</nextinput>
</engine>

=== coupelon/tdrop/tdengines/xml/voilafr.xml
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>Voila France</name>
  <separator value="+" />
	<charset>ISO-8859-1</charset>
	<terms>http://aide.voila.fr/About/aspects_legaux.html</terms>
	<query method="GET">
		<url>http://search.ke.voila.fr/S/voila</url>
		<inputfield name="kw" value="%q" />
  </query>
  <result>
    <regexp><![CDATA[lr_title[^>]*>(.*?)</a>.*?lr_content[^>]*>(.*?)</a>.*?lr_displink[^>]*>(http://|)(.*?)</a>]]></regexp>
    <field num="1" striphtml="yes" name="title" />
    <field num="2" striphtml="yes" name="abstract" />
    <field num="4" comparable="yes" striphtml="yes" escape="no" name="url">http://%s</field>
  </result>
	<nextinput method="GET">
		<regexp>suivante"\s+href="([^"]*)"</regexp>
		<inputfield escape="no" num="1" name="" value="%s" />
	</nextinput>
</engine>

=== coupelon/tdrop/tdengines/xml/googlefr.xml
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>Google France</name>
  <separator value="+" />
	<charset>UTF-8</charset>
	<terms>http://www.google.com/accounts/TOS</terms>
	<query method="GET">
		<url>http://www.google.fr/search</url>
		<inputfield name="q" value="%q" />
		<inputfield name="hl" value="fr" />
		<inputfield name="ie" value ="UTF-8" />
		<inputfield name="oe" value ="UTF-8" />
		<inputfield name="cr" value ="countryFR" />
  </query>
  <result>
		<!--regexp>&lt;a\s+class=l\s+href="([^"]*)"&gt;(.*?)&lt;/a</regexp-->
		<regexp><![CDATA[<a\s+class=l\s+href="([^"]*)">(.*?)</a>(.*?)<br>]]></regexp>
		<field num="1" comparable="yes" name="url" />
		<field num="2" striphtml="yes" name="title" />
		<field num="3" striphtml="yes" name="abstract" />
  </result>
	<nextinput method="GET">
		<regexp>&lt;a href=/search\?([^&gt;]*)&gt;&lt;img src=</regexp>
		<url>http://www.google.com/search</url>
		<inputfield escape="no" num="1" name="" value="%s" />
	</nextinput>
</engine>

=== coupelon/tdrop/tags/1.5/tdengines/xml/citeseer.xml
<!--
# Copyright (C) 2006 Olivier COUPELON

# This file is part of Teardrop.
#
# Teardrop is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Teardrop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Teardrop; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
-->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>CiteSeer</name>
  <separator value="+" />
	<charset>ISO-8859-1</charset>
	<query method="GET">
		<url>http://citeseer.ist.psu.edu/cis</url>
		<inputfield name="q" value="%q" />
		<inputfield name="cs" value="1" />
  </query>
  <result>
		<regexp><![CDATA[<!--RIS--><a href="([^"]*)">([^>]*)</a>.*?color=black>(.*?)</font>]]></regexp>
		<field num="1" comparable="yes" name="url" />
		<field num="2" name="title" />
		<field num="3" striphtml="yes" name="abstract" />
  </result>
	<nextinput method="GET">
    <regexp><![CDATA[<a\s+href="([^"]*)">Next\s+20</a>]]></regexp>
		<inputfield num="1" escape="no" name="" value="%s" />
	</nextinput>
</engine>

=== coupelon/tdrop/trunk/tdengines/xml/yahoo.xml
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
	<name>Yahoo!</name>
  <separator value="+" />
	<charset>UTF-8</charset>
	<terms>http://developer.yahoo.com/terms/</terms>
	<query method="GET">
		<url>http://search.yahooapis.com/WebSearchService/V1/webSearch</url>
		<inputfield name="appid" value="Teardrop" />
		<inputfield name="query" value="%q" />
		<inputfield name="results" value="10" />
  </query>
  <result>
		<!--regexp><![CDATA[<Title>([^<]*)</Title>.*?<Summary>([^<]*)</Summary>.*?<Url>([^<]*)</Url>]]></regexp-->
		<regexp><![CDATA[Title[^>]*>([^<]*)<.*?Summary[^>]*>([^<]*)<.*?Url[^>]*>([^<]*)<]]></regexp>
		<field num="3" comparable="yes" name="url" />
		<field num="1" striphtml="yes" name="title" />
		<field num="2" striphtml="yes" name="abstract" />
	</result>
	<nextinput method="GET">
		<url>http://search.yahooapis.com/WebSearchService/V1/webSearch</url>
		<inputfield name="appid" value="Teardrop" />
		<inputfield name="query" value="%q" />
		<inputfield name="results" value="10" />
		<inputfield name="start" value="%m" />
	</nextinput>
</engine>

=== coupelon/tdrop/trunk/tdengines/xml/ftpindexer.xml
<!--
Copyright 2008 Olivier COUPELON
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
 -->
<engine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="teardrop_1_0.xsd">
  <name>FTP Indexer.ru</name>
  <separator value="+" />
  <charset>windows-1251</charset>
  <terms>http://pubftp.com/agreement.html</terms>
  <query method="GET">
    <url>http://www.pubftp.com/8.php</url>
    <inputfield name="q" value="%q" />
  </query>
  <result>
    <regexp><![CDATA[a>/<a href="([^"]*)">(.*?)</a><br>]]></regexp>
    <field num="1" comparable="yes" name="url" />
    <field num="2" name="title" />
  </result>
  <nextinput method="GET">
    <url>http://www.pubftp.com/8.php</url>
    <inputfield name="q" value="%q" />
    <inputfield name="X" value="%n" />
  </nextinput>
</engine>
